//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace HerzfeldComplianceServer.Mediator_Global {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_IQueryDrivenAPI", Namespace="http://tempuri.org/")]
    public partial class QueryDrivenAPI : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback GetDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetAllRawDataOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetKnowledgeItemOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetOntologyTreeOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetReferenceConceptsOperationCompleted;
        
        private System.Threading.SendOrPostCallback GetDemographicConceptsOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateKBOperationCompleted;
        
        private System.Threading.SendOrPostCallback CalculateAbstractionsInBatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectPatientsOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public QueryDrivenAPI() {
            this.Url = global::HerzfeldComplianceServer.Properties.Settings.Default.HerzfeldComplianceServer_Mediator_Global_QueryDrivenAPI;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event GetDataCompletedEventHandler GetDataCompleted;
        
        /// <remarks/>
        public event GetAllRawDataCompletedEventHandler GetAllRawDataCompleted;
        
        /// <remarks/>
        public event GetKnowledgeItemCompletedEventHandler GetKnowledgeItemCompleted;
        
        /// <remarks/>
        public event GetOntologyTreeCompletedEventHandler GetOntologyTreeCompleted;
        
        /// <remarks/>
        public event GetReferenceConceptsCompletedEventHandler GetReferenceConceptsCompleted;
        
        /// <remarks/>
        public event GetDemographicConceptsCompletedEventHandler GetDemographicConceptsCompleted;
        
        /// <remarks/>
        public event UpdateKBCompletedEventHandler UpdateKBCompleted;
        
        /// <remarks/>
        public event CalculateAbstractionsInBatchCompletedEventHandler CalculateAbstractionsInBatchCompleted;
        
        /// <remarks/>
        public event SelectPatientsCompletedEventHandler SelectPatientsCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IQueryDrivenAPI/GetData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessEntities.Data")]
        public DataInstance[] GetData(long projectId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool projectIdSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string patientIds, int conceptId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool conceptIdSpecified, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)] long[] necessaryContexts, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)] long[] exclusionContexts, int contextFlag, [System.Xml.Serialization.XmlIgnoreAttribute()] bool contextFlagSpecified) {
            object[] results = this.Invoke("GetData", new object[] {
                        projectId,
                        projectIdSpecified,
                        patientIds,
                        conceptId,
                        conceptIdSpecified,
                        necessaryContexts,
                        exclusionContexts,
                        contextFlag,
                        contextFlagSpecified});
            return ((DataInstance[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDataAsync(long projectId, bool projectIdSpecified, string patientIds, int conceptId, bool conceptIdSpecified, long[] necessaryContexts, long[] exclusionContexts, int contextFlag, bool contextFlagSpecified) {
            this.GetDataAsync(projectId, projectIdSpecified, patientIds, conceptId, conceptIdSpecified, necessaryContexts, exclusionContexts, contextFlag, contextFlagSpecified, null);
        }
        
        /// <remarks/>
        public void GetDataAsync(long projectId, bool projectIdSpecified, string patientIds, int conceptId, bool conceptIdSpecified, long[] necessaryContexts, long[] exclusionContexts, int contextFlag, bool contextFlagSpecified, object userState) {
            if ((this.GetDataOperationCompleted == null)) {
                this.GetDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDataOperationCompleted);
            }
            this.InvokeAsync("GetData", new object[] {
                        projectId,
                        projectIdSpecified,
                        patientIds,
                        conceptId,
                        conceptIdSpecified,
                        necessaryContexts,
                        exclusionContexts,
                        contextFlag,
                        contextFlagSpecified}, this.GetDataOperationCompleted, userState);
        }
        
        private void OnGetDataOperationCompleted(object arg) {
            if ((this.GetDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDataCompleted(this, new GetDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IQueryDrivenAPI/GetAllRawData", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessEntities.Data")]
        public DataInstance[] GetAllRawData(long projectId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool projectIdSpecified, int entityId, [System.Xml.Serialization.XmlIgnoreAttribute()] bool entityIdSpecified) {
            object[] results = this.Invoke("GetAllRawData", new object[] {
                        projectId,
                        projectIdSpecified,
                        entityId,
                        entityIdSpecified});
            return ((DataInstance[])(results[0]));
        }
        
        /// <remarks/>
        public void GetAllRawDataAsync(long projectId, bool projectIdSpecified, int entityId, bool entityIdSpecified) {
            this.GetAllRawDataAsync(projectId, projectIdSpecified, entityId, entityIdSpecified, null);
        }
        
        /// <remarks/>
        public void GetAllRawDataAsync(long projectId, bool projectIdSpecified, int entityId, bool entityIdSpecified, object userState) {
            if ((this.GetAllRawDataOperationCompleted == null)) {
                this.GetAllRawDataOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetAllRawDataOperationCompleted);
            }
            this.InvokeAsync("GetAllRawData", new object[] {
                        projectId,
                        projectIdSpecified,
                        entityId,
                        entityIdSpecified}, this.GetAllRawDataOperationCompleted, userState);
        }
        
        private void OnGetAllRawDataOperationCompleted(object arg) {
            if ((this.GetAllRawDataCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetAllRawDataCompleted(this, new GetAllRawDataCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IQueryDrivenAPI/GetKnowledgeItem", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public KnowledgeInstance GetKnowledgeItem(long projectID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool projectIDSpecified, int conceptID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool conceptIDSpecified) {
            object[] results = this.Invoke("GetKnowledgeItem", new object[] {
                        projectID,
                        projectIDSpecified,
                        conceptID,
                        conceptIDSpecified});
            return ((KnowledgeInstance)(results[0]));
        }
        
        /// <remarks/>
        public void GetKnowledgeItemAsync(long projectID, bool projectIDSpecified, int conceptID, bool conceptIDSpecified) {
            this.GetKnowledgeItemAsync(projectID, projectIDSpecified, conceptID, conceptIDSpecified, null);
        }
        
        /// <remarks/>
        public void GetKnowledgeItemAsync(long projectID, bool projectIDSpecified, int conceptID, bool conceptIDSpecified, object userState) {
            if ((this.GetKnowledgeItemOperationCompleted == null)) {
                this.GetKnowledgeItemOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetKnowledgeItemOperationCompleted);
            }
            this.InvokeAsync("GetKnowledgeItem", new object[] {
                        projectID,
                        projectIDSpecified,
                        conceptID,
                        conceptIDSpecified}, this.GetKnowledgeItemOperationCompleted, userState);
        }
        
        private void OnGetKnowledgeItemOperationCompleted(object arg) {
            if ((this.GetKnowledgeItemCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetKnowledgeItemCompleted(this, new GetKnowledgeItemCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IQueryDrivenAPI/GetOntologyTree", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public OntologyTreeNode GetOntologyTree(long projectID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool projectIDSpecified) {
            object[] results = this.Invoke("GetOntologyTree", new object[] {
                        projectID,
                        projectIDSpecified});
            return ((OntologyTreeNode)(results[0]));
        }
        
        /// <remarks/>
        public void GetOntologyTreeAsync(long projectID, bool projectIDSpecified) {
            this.GetOntologyTreeAsync(projectID, projectIDSpecified, null);
        }
        
        /// <remarks/>
        public void GetOntologyTreeAsync(long projectID, bool projectIDSpecified, object userState) {
            if ((this.GetOntologyTreeOperationCompleted == null)) {
                this.GetOntologyTreeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetOntologyTreeOperationCompleted);
            }
            this.InvokeAsync("GetOntologyTree", new object[] {
                        projectID,
                        projectIDSpecified}, this.GetOntologyTreeOperationCompleted, userState);
        }
        
        private void OnGetOntologyTreeOperationCompleted(object arg) {
            if ((this.GetOntologyTreeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetOntologyTreeCompleted(this, new GetOntologyTreeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IQueryDrivenAPI/GetReferenceConcepts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessEntities.TAK")]
        public KnowledgeInstance[] GetReferenceConcepts(long projectID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool projectIDSpecified) {
            object[] results = this.Invoke("GetReferenceConcepts", new object[] {
                        projectID,
                        projectIDSpecified});
            return ((KnowledgeInstance[])(results[0]));
        }
        
        /// <remarks/>
        public void GetReferenceConceptsAsync(long projectID, bool projectIDSpecified) {
            this.GetReferenceConceptsAsync(projectID, projectIDSpecified, null);
        }
        
        /// <remarks/>
        public void GetReferenceConceptsAsync(long projectID, bool projectIDSpecified, object userState) {
            if ((this.GetReferenceConceptsOperationCompleted == null)) {
                this.GetReferenceConceptsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetReferenceConceptsOperationCompleted);
            }
            this.InvokeAsync("GetReferenceConcepts", new object[] {
                        projectID,
                        projectIDSpecified}, this.GetReferenceConceptsOperationCompleted, userState);
        }
        
        private void OnGetReferenceConceptsOperationCompleted(object arg) {
            if ((this.GetReferenceConceptsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetReferenceConceptsCompleted(this, new GetReferenceConceptsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IQueryDrivenAPI/GetDemographicConcepts", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessEntities.TAK")]
        public KnowledgeInstance[] GetDemographicConcepts(long projectID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool projectIDSpecified) {
            object[] results = this.Invoke("GetDemographicConcepts", new object[] {
                        projectID,
                        projectIDSpecified});
            return ((KnowledgeInstance[])(results[0]));
        }
        
        /// <remarks/>
        public void GetDemographicConceptsAsync(long projectID, bool projectIDSpecified) {
            this.GetDemographicConceptsAsync(projectID, projectIDSpecified, null);
        }
        
        /// <remarks/>
        public void GetDemographicConceptsAsync(long projectID, bool projectIDSpecified, object userState) {
            if ((this.GetDemographicConceptsOperationCompleted == null)) {
                this.GetDemographicConceptsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnGetDemographicConceptsOperationCompleted);
            }
            this.InvokeAsync("GetDemographicConcepts", new object[] {
                        projectID,
                        projectIDSpecified}, this.GetDemographicConceptsOperationCompleted, userState);
        }
        
        private void OnGetDemographicConceptsOperationCompleted(object arg) {
            if ((this.GetDemographicConceptsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.GetDemographicConceptsCompleted(this, new GetDemographicConceptsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IQueryDrivenAPI/UpdateKB", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void UpdateKB(long projectID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool projectIDSpecified, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")] string[] files) {
            this.Invoke("UpdateKB", new object[] {
                        projectID,
                        projectIDSpecified,
                        files});
        }
        
        /// <remarks/>
        public void UpdateKBAsync(long projectID, bool projectIDSpecified, string[] files) {
            this.UpdateKBAsync(projectID, projectIDSpecified, files, null);
        }
        
        /// <remarks/>
        public void UpdateKBAsync(long projectID, bool projectIDSpecified, string[] files, object userState) {
            if ((this.UpdateKBOperationCompleted == null)) {
                this.UpdateKBOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateKBOperationCompleted);
            }
            this.InvokeAsync("UpdateKB", new object[] {
                        projectID,
                        projectIDSpecified,
                        files}, this.UpdateKBOperationCompleted, userState);
        }
        
        private void OnUpdateKBOperationCompleted(object arg) {
            if ((this.UpdateKBCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateKBCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IQueryDrivenAPI/CalculateAbstractionsInBatch", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void CalculateAbstractionsInBatch(long projectID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool projectIDSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string entityIds, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string concepts, [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)] [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)] long[] necessaryContexts, int contextFlag, [System.Xml.Serialization.XmlIgnoreAttribute()] bool contextFlagSpecified, out bool CalculateAbstractionsInBatchResult, [System.Xml.Serialization.XmlIgnoreAttribute()] out bool CalculateAbstractionsInBatchResultSpecified) {
            object[] results = this.Invoke("CalculateAbstractionsInBatch", new object[] {
                        projectID,
                        projectIDSpecified,
                        entityIds,
                        concepts,
                        necessaryContexts,
                        contextFlag,
                        contextFlagSpecified});
            CalculateAbstractionsInBatchResult = ((bool)(results[0]));
            CalculateAbstractionsInBatchResultSpecified = ((bool)(results[1]));
        }
        
        /// <remarks/>
        public void CalculateAbstractionsInBatchAsync(long projectID, bool projectIDSpecified, string entityIds, string concepts, long[] necessaryContexts, int contextFlag, bool contextFlagSpecified) {
            this.CalculateAbstractionsInBatchAsync(projectID, projectIDSpecified, entityIds, concepts, necessaryContexts, contextFlag, contextFlagSpecified, null);
        }
        
        /// <remarks/>
        public void CalculateAbstractionsInBatchAsync(long projectID, bool projectIDSpecified, string entityIds, string concepts, long[] necessaryContexts, int contextFlag, bool contextFlagSpecified, object userState) {
            if ((this.CalculateAbstractionsInBatchOperationCompleted == null)) {
                this.CalculateAbstractionsInBatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnCalculateAbstractionsInBatchOperationCompleted);
            }
            this.InvokeAsync("CalculateAbstractionsInBatch", new object[] {
                        projectID,
                        projectIDSpecified,
                        entityIds,
                        concepts,
                        necessaryContexts,
                        contextFlag,
                        contextFlagSpecified}, this.CalculateAbstractionsInBatchOperationCompleted, userState);
        }
        
        private void OnCalculateAbstractionsInBatchOperationCompleted(object arg) {
            if ((this.CalculateAbstractionsInBatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.CalculateAbstractionsInBatchCompleted(this, new CalculateAbstractionsInBatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/IQueryDrivenAPI/SelectPatients", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [return: System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public int[] SelectPatients(long projectID, [System.Xml.Serialization.XmlIgnoreAttribute()] bool projectIDSpecified, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] SelectPatientsQuery query) {
            object[] results = this.Invoke("SelectPatients", new object[] {
                        projectID,
                        projectIDSpecified,
                        query});
            return ((int[])(results[0]));
        }
        
        /// <remarks/>
        public void SelectPatientsAsync(long projectID, bool projectIDSpecified, SelectPatientsQuery query) {
            this.SelectPatientsAsync(projectID, projectIDSpecified, query, null);
        }
        
        /// <remarks/>
        public void SelectPatientsAsync(long projectID, bool projectIDSpecified, SelectPatientsQuery query, object userState) {
            if ((this.SelectPatientsOperationCompleted == null)) {
                this.SelectPatientsOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectPatientsOperationCompleted);
            }
            this.InvokeAsync("SelectPatients", new object[] {
                        projectID,
                        projectIDSpecified,
                        query}, this.SelectPatientsOperationCompleted, userState);
        }
        
        private void OnSelectPatientsOperationCompleted(object arg) {
            if ((this.SelectPatientsCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectPatientsCompleted(this, new SelectPatientsCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessEntities.Data")]
    public partial class DataInstance {
        
        private string conceptNamek__BackingFieldField;
        
        private System.DateTime endTimek__BackingFieldField;
        
        private int entityIdk__BackingFieldField;
        
        private System.DateTime startTimek__BackingFieldField;
        
        private string valuek__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ConceptName>k__BackingField", IsNullable=true)]
        public string ConceptNamek__BackingField {
            get {
                return this.conceptNamek__BackingFieldField;
            }
            set {
                this.conceptNamek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<EndTime>k__BackingField")]
        public System.DateTime EndTimek__BackingField {
            get {
                return this.endTimek__BackingFieldField;
            }
            set {
                this.endTimek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<EntityId>k__BackingField")]
        public int EntityIdk__BackingField {
            get {
                return this.entityIdk__BackingFieldField;
            }
            set {
                this.entityIdk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<StartTime>k__BackingField")]
        public System.DateTime StartTimek__BackingField {
            get {
                return this.startTimek__BackingFieldField;
            }
            set {
                this.startTimek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<Value>k__BackingField", IsNullable=true)]
        public string Valuek__BackingField {
            get {
                return this.valuek__BackingFieldField;
            }
            set {
                this.valuek__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public partial class Gap {
        
        private nachmanLogicOperators operatorField;
        
        private bool operatorFieldSpecified;
        
        private int maxDifferenceField;
        
        private bool maxDifferenceFieldSpecified;
        
        private int minDifferenceField;
        
        private bool minDifferenceFieldSpecified;
        
        private TimeGranularityUnits timeUnitField;
        
        private bool timeUnitFieldSpecified;
        
        /// <remarks/>
        public nachmanLogicOperators Operator {
            get {
                return this.operatorField;
            }
            set {
                this.operatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OperatorSpecified {
            get {
                return this.operatorFieldSpecified;
            }
            set {
                this.operatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int maxDifference {
            get {
                return this.maxDifferenceField;
            }
            set {
                this.maxDifferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxDifferenceSpecified {
            get {
                return this.maxDifferenceFieldSpecified;
            }
            set {
                this.maxDifferenceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int minDifference {
            get {
                return this.minDifferenceField;
            }
            set {
                this.minDifferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minDifferenceSpecified {
            get {
                return this.minDifferenceFieldSpecified;
            }
            set {
                this.minDifferenceFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public TimeGranularityUnits timeUnit {
            get {
                return this.timeUnitField;
            }
            set {
                this.timeUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool timeUnitSpecified {
            get {
                return this.timeUnitFieldSpecified;
            }
            set {
                this.timeUnitFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public enum nachmanLogicOperators {
        
        /// <remarks/>
        Equals,
        
        /// <remarks/>
        NotEquals,
        
        /// <remarks/>
        Greater,
        
        /// <remarks/>
        GreaterOrEquals,
        
        /// <remarks/>
        Smaller,
        
        /// <remarks/>
        SmallerOrEquals,
        
        /// <remarks/>
        Between,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public enum TimeGranularityUnits {
        
        /// <remarks/>
        Seconds,
        
        /// <remarks/>
        Minutes,
        
        /// <remarks/>
        Hours,
        
        /// <remarks/>
        Days,
        
        /// <remarks/>
        Weeks,
        
        /// <remarks/>
        Months,
        
        /// <remarks/>
        Years,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public partial class PairwiseConstraint {
        
        private Gap end_EndField;
        
        private Gap end_StartField;
        
        private Relations relationField;
        
        private bool relationFieldSpecified;
        
        private Gap start_EndField;
        
        private Gap start_StartField;
        
        private nachmanBoundaryPointTypes boundaryPointAField;
        
        private bool boundaryPointAFieldSpecified;
        
        private nachmanBoundaryPointTypes boundaryPointBField;
        
        private bool boundaryPointBFieldSpecified;
        
        private string componentAliasAField;
        
        private string componentAliasBField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Gap End_End {
            get {
                return this.end_EndField;
            }
            set {
                this.end_EndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Gap End_Start {
            get {
                return this.end_StartField;
            }
            set {
                this.end_StartField = value;
            }
        }
        
        /// <remarks/>
        public Relations Relation {
            get {
                return this.relationField;
            }
            set {
                this.relationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool RelationSpecified {
            get {
                return this.relationFieldSpecified;
            }
            set {
                this.relationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Gap Start_End {
            get {
                return this.start_EndField;
            }
            set {
                this.start_EndField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Gap Start_Start {
            get {
                return this.start_StartField;
            }
            set {
                this.start_StartField = value;
            }
        }
        
        /// <remarks/>
        public nachmanBoundaryPointTypes boundaryPointA {
            get {
                return this.boundaryPointAField;
            }
            set {
                this.boundaryPointAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool boundaryPointASpecified {
            get {
                return this.boundaryPointAFieldSpecified;
            }
            set {
                this.boundaryPointAFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public nachmanBoundaryPointTypes boundaryPointB {
            get {
                return this.boundaryPointBField;
            }
            set {
                this.boundaryPointBField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool boundaryPointBSpecified {
            get {
                return this.boundaryPointBFieldSpecified;
            }
            set {
                this.boundaryPointBFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string componentAliasA {
            get {
                return this.componentAliasAField;
            }
            set {
                this.componentAliasAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string componentAliasB {
            get {
                return this.componentAliasBField;
            }
            set {
                this.componentAliasBField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public enum Relations {
        
        /// <remarks/>
        After,
        
        /// <remarks/>
        Before,
        
        /// <remarks/>
        Equals,
        
        /// <remarks/>
        Meet,
        
        /// <remarks/>
        Overlaps,
        
        /// <remarks/>
        Starts,
        
        /// <remarks/>
        Finishes,
        
        /// <remarks/>
        Containts,
        
        /// <remarks/>
        Custom,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public enum nachmanBoundaryPointTypes {
        
        /// <remarks/>
        Start,
        
        /// <remarks/>
        End,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public partial class StatisticalConstraint {
        
        private nachmanLogicOperators logicOperatorField;
        
        private bool logicOperatorFieldSpecified;
        
        private RawDataDelegateFunction populationDataDelegateFunctionField;
        
        private bool populationDataDelegateFunctionFieldSpecified;
        
        private RawDataDelegateFunction subjectDataDelegateFunctionField;
        
        private bool subjectDataDelegateFunctionFieldSpecified;
        
        /// <remarks/>
        public nachmanLogicOperators logicOperator {
            get {
                return this.logicOperatorField;
            }
            set {
                this.logicOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool logicOperatorSpecified {
            get {
                return this.logicOperatorFieldSpecified;
            }
            set {
                this.logicOperatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public RawDataDelegateFunction populationDataDelegateFunction {
            get {
                return this.populationDataDelegateFunctionField;
            }
            set {
                this.populationDataDelegateFunctionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool populationDataDelegateFunctionSpecified {
            get {
                return this.populationDataDelegateFunctionFieldSpecified;
            }
            set {
                this.populationDataDelegateFunctionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public RawDataDelegateFunction subjectDataDelegateFunction {
            get {
                return this.subjectDataDelegateFunctionField;
            }
            set {
                this.subjectDataDelegateFunctionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool subjectDataDelegateFunctionSpecified {
            get {
                return this.subjectDataDelegateFunctionFieldSpecified;
            }
            set {
                this.subjectDataDelegateFunctionFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public enum RawDataDelegateFunction {
        
        /// <remarks/>
        none,
        
        /// <remarks/>
        Min,
        
        /// <remarks/>
        Max,
        
        /// <remarks/>
        Avg,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public partial class ProportionConstraint {
        
        private double maxThresholdField;
        
        private bool maxThresholdFieldSpecified;
        
        private double minThresholdField;
        
        private bool minThresholdFieldSpecified;
        
        /// <remarks/>
        public double maxThreshold {
            get {
                return this.maxThresholdField;
            }
            set {
                this.maxThresholdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxThresholdSpecified {
            get {
                return this.maxThresholdFieldSpecified;
            }
            set {
                this.maxThresholdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double minThreshold {
            get {
                return this.minThresholdField;
            }
            set {
                this.minThresholdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minThresholdSpecified {
            get {
                return this.minThresholdFieldSpecified;
            }
            set {
                this.minThresholdFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public partial class NachmanTimeSpan {
        
        private int daysField;
        
        private bool daysFieldSpecified;
        
        private int hoursField;
        
        private bool hoursFieldSpecified;
        
        private int minutesField;
        
        private bool minutesFieldSpecified;
        
        private int monthField;
        
        private bool monthFieldSpecified;
        
        private int secondsField;
        
        private bool secondsFieldSpecified;
        
        private int yearsField;
        
        private bool yearsFieldSpecified;
        
        /// <remarks/>
        public int days {
            get {
                return this.daysField;
            }
            set {
                this.daysField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool daysSpecified {
            get {
                return this.daysFieldSpecified;
            }
            set {
                this.daysFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int hours {
            get {
                return this.hoursField;
            }
            set {
                this.hoursField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hoursSpecified {
            get {
                return this.hoursFieldSpecified;
            }
            set {
                this.hoursFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int minutes {
            get {
                return this.minutesField;
            }
            set {
                this.minutesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minutesSpecified {
            get {
                return this.minutesFieldSpecified;
            }
            set {
                this.minutesFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int month {
            get {
                return this.monthField;
            }
            set {
                this.monthField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool monthSpecified {
            get {
                return this.monthFieldSpecified;
            }
            set {
                this.monthFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int seconds {
            get {
                return this.secondsField;
            }
            set {
                this.secondsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secondsSpecified {
            get {
                return this.secondsFieldSpecified;
            }
            set {
                this.secondsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int years {
            get {
                return this.yearsField;
            }
            set {
                this.yearsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool yearsSpecified {
            get {
                return this.yearsFieldSpecified;
            }
            set {
                this.yearsFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public partial class DurationConstraint {
        
        private TimeGranularityUnits durationTimeUnitField;
        
        private bool durationTimeUnitFieldSpecified;
        
        private double maxDurationField;
        
        private bool maxDurationFieldSpecified;
        
        private double minDurationField;
        
        private bool minDurationFieldSpecified;
        
        /// <remarks/>
        public TimeGranularityUnits DurationTimeUnit {
            get {
                return this.durationTimeUnitField;
            }
            set {
                this.durationTimeUnitField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DurationTimeUnitSpecified {
            get {
                return this.durationTimeUnitFieldSpecified;
            }
            set {
                this.durationTimeUnitFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double maxDuration {
            get {
                return this.maxDurationField;
            }
            set {
                this.maxDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool maxDurationSpecified {
            get {
                return this.maxDurationFieldSpecified;
            }
            set {
                this.maxDurationFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double minDuration {
            get {
                return this.minDurationField;
            }
            set {
                this.minDurationField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool minDurationSpecified {
            get {
                return this.minDurationFieldSpecified;
            }
            set {
                this.minDurationFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public partial class TimeConstraint {
        
        private DurationConstraint durationConstraitnsField;
        
        private System.DateTime earliestEndPointField;
        
        private bool earliestEndPointFieldSpecified;
        
        private System.DateTime earliestStartPointField;
        
        private bool earliestStartPointFieldSpecified;
        
        private System.DateTime endPointField;
        
        private bool endPointFieldSpecified;
        
        private bool endTimeAsRangeField;
        
        private bool endTimeAsRangeFieldSpecified;
        
        private bool isAbsTimeField;
        
        private bool isAbsTimeFieldSpecified;
        
        private System.DateTime latestEndPointField;
        
        private bool latestEndPointFieldSpecified;
        
        private System.DateTime latestStartPointField;
        
        private bool latestStartPointFieldSpecified;
        
        private nachmanBoundaryPointTypes referenceBoundaryPointField;
        
        private bool referenceBoundaryPointFieldSpecified;
        
        private ConceptKnowledge referencePointField;
        
        private PositionNumberTypes referencePositionNumberField;
        
        private bool referencePositionNumberFieldSpecified;
        
        private NachmanTimeSpan relativeEarliestEndPointField;
        
        private NachmanTimeSpan relativeEarliestStartPointField;
        
        private NachmanTimeSpan relativeEndPointField;
        
        private NachmanTimeSpan relativeLatestEndPointField;
        
        private NachmanTimeSpan relativeLatestStartPointField;
        
        private NachmanTimeSpan relativeStartPointField;
        
        private System.DateTime startPointField;
        
        private bool startPointFieldSpecified;
        
        private bool startTimeAsRangeField;
        
        private bool startTimeAsRangeFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public DurationConstraint DurationConstraitns {
            get {
                return this.durationConstraitnsField;
            }
            set {
                this.durationConstraitnsField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EarliestEndPoint {
            get {
                return this.earliestEndPointField;
            }
            set {
                this.earliestEndPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EarliestEndPointSpecified {
            get {
                return this.earliestEndPointFieldSpecified;
            }
            set {
                this.earliestEndPointFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EarliestStartPoint {
            get {
                return this.earliestStartPointField;
            }
            set {
                this.earliestStartPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EarliestStartPointSpecified {
            get {
                return this.earliestStartPointFieldSpecified;
            }
            set {
                this.earliestStartPointFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime EndPoint {
            get {
                return this.endPointField;
            }
            set {
                this.endPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndPointSpecified {
            get {
                return this.endPointFieldSpecified;
            }
            set {
                this.endPointFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool EndTimeAsRange {
            get {
                return this.endTimeAsRangeField;
            }
            set {
                this.endTimeAsRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EndTimeAsRangeSpecified {
            get {
                return this.endTimeAsRangeFieldSpecified;
            }
            set {
                this.endTimeAsRangeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool IsAbsTime {
            get {
                return this.isAbsTimeField;
            }
            set {
                this.isAbsTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IsAbsTimeSpecified {
            get {
                return this.isAbsTimeFieldSpecified;
            }
            set {
                this.isAbsTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LatestEndPoint {
            get {
                return this.latestEndPointField;
            }
            set {
                this.latestEndPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatestEndPointSpecified {
            get {
                return this.latestEndPointFieldSpecified;
            }
            set {
                this.latestEndPointFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime LatestStartPoint {
            get {
                return this.latestStartPointField;
            }
            set {
                this.latestStartPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool LatestStartPointSpecified {
            get {
                return this.latestStartPointFieldSpecified;
            }
            set {
                this.latestStartPointFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public nachmanBoundaryPointTypes ReferenceBoundaryPoint {
            get {
                return this.referenceBoundaryPointField;
            }
            set {
                this.referenceBoundaryPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferenceBoundaryPointSpecified {
            get {
                return this.referenceBoundaryPointFieldSpecified;
            }
            set {
                this.referenceBoundaryPointFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ConceptKnowledge ReferencePoint {
            get {
                return this.referencePointField;
            }
            set {
                this.referencePointField = value;
            }
        }
        
        /// <remarks/>
        public PositionNumberTypes ReferencePositionNumber {
            get {
                return this.referencePositionNumberField;
            }
            set {
                this.referencePositionNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ReferencePositionNumberSpecified {
            get {
                return this.referencePositionNumberFieldSpecified;
            }
            set {
                this.referencePositionNumberFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NachmanTimeSpan RelativeEarliestEndPoint {
            get {
                return this.relativeEarliestEndPointField;
            }
            set {
                this.relativeEarliestEndPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NachmanTimeSpan RelativeEarliestStartPoint {
            get {
                return this.relativeEarliestStartPointField;
            }
            set {
                this.relativeEarliestStartPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NachmanTimeSpan RelativeEndPoint {
            get {
                return this.relativeEndPointField;
            }
            set {
                this.relativeEndPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NachmanTimeSpan RelativeLatestEndPoint {
            get {
                return this.relativeLatestEndPointField;
            }
            set {
                this.relativeLatestEndPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NachmanTimeSpan RelativeLatestStartPoint {
            get {
                return this.relativeLatestStartPointField;
            }
            set {
                this.relativeLatestStartPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public NachmanTimeSpan RelativeStartPoint {
            get {
                return this.relativeStartPointField;
            }
            set {
                this.relativeStartPointField = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime StartPoint {
            get {
                return this.startPointField;
            }
            set {
                this.startPointField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartPointSpecified {
            get {
                return this.startPointFieldSpecified;
            }
            set {
                this.startPointFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public bool StartTimeAsRange {
            get {
                return this.startTimeAsRangeField;
            }
            set {
                this.startTimeAsRangeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartTimeAsRangeSpecified {
            get {
                return this.startTimeAsRangeFieldSpecified;
            }
            set {
                this.startTimeAsRangeFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public partial class ConceptKnowledge {
        
        private long idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        private nachmanOutputTypes outputTypeField;
        
        private bool outputTypeFieldSpecified;
        
        private string[] statesField;
        
        /// <remarks/>
        public long ID {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IDSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        public nachmanOutputTypes OutputType {
            get {
                return this.outputTypeField;
            }
            set {
                this.outputTypeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool OutputTypeSpecified {
            get {
                return this.outputTypeFieldSpecified;
            }
            set {
                this.outputTypeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] States {
            get {
                return this.statesField;
            }
            set {
                this.statesField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public enum nachmanOutputTypes {
        
        /// <remarks/>
        Numeric,
        
        /// <remarks/>
        Symbolic,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public enum PositionNumberTypes {
        
        /// <remarks/>
        First,
        
        /// <remarks/>
        Second,
        
        /// <remarks/>
        Third,
        
        /// <remarks/>
        Fourth,
        
        /// <remarks/>
        Fifth,
        
        /// <remarks/>
        Last,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public partial class KBConstraint {
        
        private ConceptKnowledge conceptKnowledgeField;
        
        private TimeConstraint timeConstraintField;
        
        private nachmanValueConstraint valueConstraintField;
        
        private string componentAliasField;
        
        private ProportionConstraint proportionConstraintField;
        
        private StatisticalConstraint statisticalConstraintField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ConceptKnowledge ConceptKnowledge {
            get {
                return this.conceptKnowledgeField;
            }
            set {
                this.conceptKnowledgeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public TimeConstraint TimeConstraint {
            get {
                return this.timeConstraintField;
            }
            set {
                this.timeConstraintField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public nachmanValueConstraint ValueConstraint {
            get {
                return this.valueConstraintField;
            }
            set {
                this.valueConstraintField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string componentAlias {
            get {
                return this.componentAliasField;
            }
            set {
                this.componentAliasField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ProportionConstraint proportionConstraint {
            get {
                return this.proportionConstraintField;
            }
            set {
                this.proportionConstraintField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public StatisticalConstraint statisticalConstraint {
            get {
                return this.statisticalConstraintField;
            }
            set {
                this.statisticalConstraintField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public partial class nachmanValueConstraint {
        
        private nachmanLogicOperators logicOperatorField;
        
        private bool logicOperatorFieldSpecified;
        
        private double numericMaxValueField;
        
        private bool numericMaxValueFieldSpecified;
        
        private double numericMinValueField;
        
        private bool numericMinValueFieldSpecified;
        
        private string symbolicMaxValueField;
        
        private string symbolicMinValueField;
        
        private string symbolicValueField;
        
        /// <remarks/>
        public nachmanLogicOperators logicOperator {
            get {
                return this.logicOperatorField;
            }
            set {
                this.logicOperatorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool logicOperatorSpecified {
            get {
                return this.logicOperatorFieldSpecified;
            }
            set {
                this.logicOperatorFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double numericMaxValue {
            get {
                return this.numericMaxValueField;
            }
            set {
                this.numericMaxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numericMaxValueSpecified {
            get {
                return this.numericMaxValueFieldSpecified;
            }
            set {
                this.numericMaxValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double numericMinValue {
            get {
                return this.numericMinValueField;
            }
            set {
                this.numericMinValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool numericMinValueSpecified {
            get {
                return this.numericMinValueFieldSpecified;
            }
            set {
                this.numericMinValueFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string symbolicMaxValue {
            get {
                return this.symbolicMaxValueField;
            }
            set {
                this.symbolicMaxValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string symbolicMinValue {
            get {
                return this.symbolicMinValueField;
            }
            set {
                this.symbolicMinValueField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string symbolicValue {
            get {
                return this.symbolicValueField;
            }
            set {
                this.symbolicValueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public partial class DemographicConstraint {
        
        private nachmanValueConstraint[] valueConstraintsField;
        
        private LogicRelations valueConstraintsRelationsField;
        
        private bool valueConstraintsRelationsFieldSpecified;
        
        private ConceptKnowledge demographicConceptField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public nachmanValueConstraint[] ValueConstraints {
            get {
                return this.valueConstraintsField;
            }
            set {
                this.valueConstraintsField = value;
            }
        }
        
        /// <remarks/>
        public LogicRelations ValueConstraintsRelations {
            get {
                return this.valueConstraintsRelationsField;
            }
            set {
                this.valueConstraintsRelationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ValueConstraintsRelationsSpecified {
            get {
                return this.valueConstraintsRelationsFieldSpecified;
            }
            set {
                this.valueConstraintsRelationsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public ConceptKnowledge demographicConcept {
            get {
                return this.demographicConceptField;
            }
            set {
                this.demographicConceptField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public enum LogicRelations {
        
        /// <remarks/>
        AND,
        
        /// <remarks/>
        OR,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/NachmanBE")]
    public partial class SelectPatientsQuery {
        
        private DemographicConstraint[] demographicConstraintsField;
        
        private LogicRelations demographicConstraintsRelationsField;
        
        private bool demographicConstraintsRelationsFieldSpecified;
        
        private KBConstraint[] kBConstraintsField;
        
        private LogicRelations kBConstraintsRelationsField;
        
        private bool kBConstraintsRelationsFieldSpecified;
        
        private PairwiseConstraint[] temporalPairwiseConstraintsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public DemographicConstraint[] DemographicConstraints {
            get {
                return this.demographicConstraintsField;
            }
            set {
                this.demographicConstraintsField = value;
            }
        }
        
        /// <remarks/>
        public LogicRelations DemographicConstraintsRelations {
            get {
                return this.demographicConstraintsRelationsField;
            }
            set {
                this.demographicConstraintsRelationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DemographicConstraintsRelationsSpecified {
            get {
                return this.demographicConstraintsRelationsFieldSpecified;
            }
            set {
                this.demographicConstraintsRelationsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public KBConstraint[] KBConstraints {
            get {
                return this.kBConstraintsField;
            }
            set {
                this.kBConstraintsField = value;
            }
        }
        
        /// <remarks/>
        public LogicRelations KBConstraintsRelations {
            get {
                return this.kBConstraintsRelationsField;
            }
            set {
                this.kBConstraintsRelationsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool KBConstraintsRelationsSpecified {
            get {
                return this.kBConstraintsRelationsFieldSpecified;
            }
            set {
                this.kBConstraintsRelationsFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public PairwiseConstraint[] TemporalPairwiseConstraints {
            get {
                return this.temporalPairwiseConstraintsField;
            }
            set {
                this.temporalPairwiseConstraintsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessEntities.TAK")]
    public partial class OntologyTreeNode {
        
        private KnowledgeInstance kiField;
        
        private string nameField;
        
        private OntologyTreeNode[] sonsField;
        
        private string groupField;
        
        private bool isFolderField;
        
        private bool isFolderFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public KnowledgeInstance KI {
            get {
                return this.kiField;
            }
            set {
                this.kiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string Name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public OntologyTreeNode[] Sons {
            get {
                return this.sonsField;
            }
            set {
                this.sonsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string group {
            get {
                return this.groupField;
            }
            set {
                this.groupField = value;
            }
        }
        
        /// <remarks/>
        public bool isFolder {
            get {
                return this.isFolderField;
            }
            set {
                this.isFolderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool isFolderSpecified {
            get {
                return this.isFolderFieldSpecified;
            }
            set {
                this.isFolderFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3062.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/BusinessEntities.TAK")]
    public partial class KnowledgeInstance {
        
        private long[] derivedFromField;
        
        private long conceptIDk__BackingFieldField;
        
        private string conceptNamek__BackingFieldField;
        
        private bool isTemporalk__BackingFieldField;
        
        private string[] outputAllowedValuesk__BackingFieldField;
        
        private string outputTypek__BackingFieldField;
        
        private double scaleMaxValuek__BackingFieldField;
        
        private double scaleMinValuek__BackingFieldField;
        
        private string unitTypek__BackingFieldField;
        
        private string conceptTypek__BackingFieldField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays", IsNullable=false)]
        public long[] DerivedFrom {
            get {
                return this.derivedFromField;
            }
            set {
                this.derivedFromField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ConceptID>k__BackingField")]
        public long ConceptIDk__BackingField {
            get {
                return this.conceptIDk__BackingFieldField;
            }
            set {
                this.conceptIDk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ConceptName>k__BackingField", IsNullable=true)]
        public string ConceptNamek__BackingField {
            get {
                return this.conceptNamek__BackingFieldField;
            }
            set {
                this.conceptNamek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<IsTemporal>k__BackingField")]
        public bool IsTemporalk__BackingField {
            get {
                return this.isTemporalk__BackingFieldField;
            }
            set {
                this.isTemporalk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute("<OutputAllowedValues>k__BackingField", IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.microsoft.com/2003/10/Serialization/Arrays")]
        public string[] OutputAllowedValuesk__BackingField {
            get {
                return this.outputAllowedValuesk__BackingFieldField;
            }
            set {
                this.outputAllowedValuesk__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<OutputType>k__BackingField", IsNullable=true)]
        public string OutputTypek__BackingField {
            get {
                return this.outputTypek__BackingFieldField;
            }
            set {
                this.outputTypek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ScaleMaxValue>k__BackingField")]
        public double ScaleMaxValuek__BackingField {
            get {
                return this.scaleMaxValuek__BackingFieldField;
            }
            set {
                this.scaleMaxValuek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<ScaleMinValue>k__BackingField")]
        public double ScaleMinValuek__BackingField {
            get {
                return this.scaleMinValuek__BackingFieldField;
            }
            set {
                this.scaleMinValuek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<UnitType>k__BackingField", IsNullable=true)]
        public string UnitTypek__BackingField {
            get {
                return this.unitTypek__BackingFieldField;
            }
            set {
                this.unitTypek__BackingFieldField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("<conceptType>k__BackingField", IsNullable=true)]
        public string conceptTypek__BackingField {
            get {
                return this.conceptTypek__BackingFieldField;
            }
            set {
                this.conceptTypek__BackingFieldField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetDataCompletedEventHandler(object sender, GetDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataInstance[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataInstance[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetAllRawDataCompletedEventHandler(object sender, GetAllRawDataCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetAllRawDataCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetAllRawDataCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public DataInstance[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((DataInstance[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetKnowledgeItemCompletedEventHandler(object sender, GetKnowledgeItemCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetKnowledgeItemCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetKnowledgeItemCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KnowledgeInstance Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KnowledgeInstance)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetOntologyTreeCompletedEventHandler(object sender, GetOntologyTreeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetOntologyTreeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetOntologyTreeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public OntologyTreeNode Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((OntologyTreeNode)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetReferenceConceptsCompletedEventHandler(object sender, GetReferenceConceptsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetReferenceConceptsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetReferenceConceptsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KnowledgeInstance[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KnowledgeInstance[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void GetDemographicConceptsCompletedEventHandler(object sender, GetDemographicConceptsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class GetDemographicConceptsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal GetDemographicConceptsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public KnowledgeInstance[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((KnowledgeInstance[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void UpdateKBCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void CalculateAbstractionsInBatchCompletedEventHandler(object sender, CalculateAbstractionsInBatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class CalculateAbstractionsInBatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal CalculateAbstractionsInBatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public bool CalculateAbstractionsInBatchResult {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public bool CalculateAbstractionsInBatchResultSpecified {
            get {
                this.RaiseExceptionIfNecessary();
                return ((bool)(this.results[1]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    public delegate void SelectPatientsCompletedEventHandler(object sender, SelectPatientsCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3062.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectPatientsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectPatientsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public int[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((int[])(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591